spring:
  datasource:
    username: network
    password: network
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/network
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true

properties:
  filter:
    attributeName: loginRes
    loginUrl: /auth/login
  minio:
    host: "https://localhost"
    port: 9000
    secure: false
    jpegType: image/jpeg
    accessToken: TQE5viifimaaSC6iSYhA
    secretToken: e9c8lPtMLbYgdYkcOGNcQxN3Y1mIdWQCvkwlDfVi
    backImgLink: backImg/
    avatarLink: avatar/
    bucket: buck-avatar