spring:
  datasource:
    username: network
    password: network
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/network
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:/db/migration
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 2MB

properties:
  filter:
    attributeName: loginRes
    loginUrl: /auth/login
  minio:
    host: "https://localhost"
    port: 9000
    secure: false
    jpegType: image/jpeg
    accessToken: TQE5viifimaaSC6iSYhA
    secretToken: e9c8lPtMLbYgdYkcOGNcQxN3Y1mIdWQCvkwlDfVi
    backImgLink: backImg/
    avatarLink: avatar/
    buckets:
      - post
      - avatar
      - background
  file:
    compresses:
      - name: post
        width: 200
        height: 200
      - name: postSub
        width: 200
        height: 200
      - name: postRecomendations
        width: 200
        height: 200
      - name: avatar
        width: 200
        height: 200
      - name: avatarMini
        width: 200
        height: 200
      - name: avatarNotifications
        width: 200
        height: 200
      - name: avatarCommonSubs
        width: 200
        height: 200
      - name: background
        width: 200
        height: 200
  jwt:
    secretKey: IhiMjRKZAGO0ecKNUXCXull5zmYgsBKsI63uGB2aoSJFukFJaSvIZfI8ACvS
    accessTokenValidity: 2
    refreshTokenValidity: 15
    tokenHeader: Authorization
    tokenPrefix: Bearer

springdoc:
  api-docs:
    path: /api-docs