spring:
  datasource:
    username: network
    password: network
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/network
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
#  flyway:
#    locations: classpath:db/migration
#    enabled: true
#    baseline-on-migrate: true