CREATE TABLE certificate
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    link      VARCHAR(255)                            NOT NULL,
    issued    VARCHAR(255)                            NOT NULL,
    unique_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_certificate PRIMARY KEY (id)
);

CREATE TABLE common_user_info
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    avatar       VARCHAR(255),
    back_photo   VARCHAR(255),
    phone_number VARCHAR(255)                            NOT NULL,
    user_id      BIGINT,
    CONSTRAINT pk_commonuserinfo PRIMARY KEY (id)
);

CREATE TABLE common_user_info_language
(
    common_user_info_id BIGINT NOT NULL,
    language_id         BIGINT NOT NULL
);

CREATE TABLE common_user_info_university
(
    common_user_info_id BIGINT NOT NULL,
    university_id       BIGINT NOT NULL
);

CREATE TABLE course
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    limk VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);

CREATE TABLE event_time
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start    TIMESTAMP WITHOUT TIME ZONE,
    end_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_eventtime PRIMARY KEY (id)
);

CREATE TABLE events
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    events_id     BIGINT                                  NOT NULL,
    is_discussion BOOLEAN                                 NOT NULL,
    is_hide_part  BOOLEAN                                 NOT NULL,
    is_weather_on BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE events_event_time
(
    event_time_id BIGINT NOT NULL,
    events_id     BIGINT NOT NULL
);

CREATE TABLE events_worth_events
(
    events_id       BIGINT NOT NULL,
    worth_events_id BIGINT NOT NULL
);

CREATE TABLE hashtags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_hashtags PRIMARY KEY (id)
);

CREATE TABLE interests
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_interests PRIMARY KEY (id)
);

CREATE TABLE job
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company     VARCHAR(255)                            NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    location    VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    duration    VARCHAR(255)                            NOT NULL,
    picture     VARCHAR(255),
    CONSTRAINT pk_job PRIMARY KEY (id)
);

CREATE TABLE language
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_language PRIMARY KEY (id)
);

CREATE TABLE member_events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_profile_id BIGINT                                  NOT NULL,
    events_id       BIGINT                                  NOT NULL,
    is_creator      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_memberevents PRIMARY KEY (id)
);

CREATE TABLE patent
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    link  VARCHAR(255)                            NOT NULL,
    place VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_patent PRIMARY KEY (id)
);

CREATE TABLE recomenadation
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lint_to_owner VARCHAR(255)                            NOT NULL,
    link_to_post  VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    grade         DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_recomenadation PRIMARY KEY (id)
);

CREATE TABLE resume
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_resume PRIMARY KEY (id)
);

CREATE TABLE resume_certificates
(
    certificates_id BIGINT NOT NULL,
    resume_id       BIGINT NOT NULL
);

CREATE TABLE resume_courses
(
    courses_id BIGINT NOT NULL,
    resume_id  BIGINT NOT NULL
);

CREATE TABLE resume_jobs
(
    jobs_id   BIGINT NOT NULL,
    resume_id BIGINT NOT NULL
);

CREATE TABLE resume_patents
(
    patents_id BIGINT NOT NULL,
    resume_id  BIGINT NOT NULL
);

CREATE TABLE resume_recomenadations
(
    recomenadations_id BIGINT NOT NULL,
    resume_id          BIGINT NOT NULL
);

CREATE TABLE resume_skills
(
    resume_id BIGINT NOT NULL,
    skills_id BIGINT NOT NULL
);

CREATE TABLE resume_volunteers
(
    resume_id     BIGINT NOT NULL,
    volunteers_id BIGINT NOT NULL
);

CREATE TABLE skill
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_skill PRIMARY KEY (id)
);

CREATE TABLE university
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_university PRIMARY KEY (id)
);

CREATE TABLE user_net
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    password            VARCHAR(255)                            NOT NULL,
    refresh_token       VARCHAR(255),
    common_user_info_id BIGINT,
    CONSTRAINT pk_user_net PRIMARY KEY (id)
);

CREATE TABLE user_profile
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    lastname   VARCHAR(255)                            NOT NULL,
    birth_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    address    VARCHAR(255),
    CONSTRAINT pk_user_profile PRIMARY KEY (id)
);

CREATE TABLE user_profile_hashtags
(
    hashtags_id     BIGINT NOT NULL,
    user_profile_id BIGINT NOT NULL
);

CREATE TABLE user_profile_interests
(
    interests_id    BIGINT NOT NULL,
    user_profile_id BIGINT NOT NULL
);

CREATE TABLE volunteer
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    place    VARCHAR(255)                            NOT NULL,
    duration VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_volunteer PRIMARY KEY (id)
);

CREATE TABLE worth_events
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price    INTEGER,
    currency VARCHAR(3),
    text     VARCHAR(255),
    CONSTRAINT pk_worth_events PRIMARY KEY (id)
);

ALTER TABLE common_user_info
    ADD CONSTRAINT uc_commonuserinfo_phone_number UNIQUE (phone_number);

ALTER TABLE common_user_info
    ADD CONSTRAINT uc_commonuserinfo_user UNIQUE (user_id);

ALTER TABLE hashtags
    ADD CONSTRAINT uc_hashtags_name UNIQUE (name);

ALTER TABLE interests
    ADD CONSTRAINT uc_interests_name UNIQUE (name);

ALTER TABLE user_net
    ADD CONSTRAINT uc_user_net_commonuserinfo UNIQUE (common_user_info_id);

ALTER TABLE user_net
    ADD CONSTRAINT uc_user_net_email UNIQUE (email);

ALTER TABLE user_net
    ADD CONSTRAINT uc_user_net_password UNIQUE (password);

ALTER TABLE user_net
    ADD CONSTRAINT uc_user_net_refresh_token UNIQUE (refresh_token);

ALTER TABLE common_user_info
    ADD CONSTRAINT FK_COMMONUSERINFO_ON_USER FOREIGN KEY (user_id) REFERENCES user_net (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_EVENTS FOREIGN KEY (events_id) REFERENCES events (id);

ALTER TABLE member_events
    ADD CONSTRAINT FK_MEMBEREVENTS_ON_EVENTS FOREIGN KEY (events_id) REFERENCES events (id);

ALTER TABLE member_events
    ADD CONSTRAINT FK_MEMBEREVENTS_ON_USERPROFILE FOREIGN KEY (user_profile_id) REFERENCES user_profile (id);

ALTER TABLE user_net
    ADD CONSTRAINT FK_USER_NET_ON_COMMONUSERINFO FOREIGN KEY (common_user_info_id) REFERENCES common_user_info (id);

ALTER TABLE common_user_info_language
    ADD CONSTRAINT fk_comuseinflan_on_common_user_info FOREIGN KEY (common_user_info_id) REFERENCES common_user_info (id);

ALTER TABLE common_user_info_language
    ADD CONSTRAINT fk_comuseinflan_on_language FOREIGN KEY (language_id) REFERENCES language (id);

ALTER TABLE common_user_info_university
    ADD CONSTRAINT fk_comuseinfuni_on_common_user_info FOREIGN KEY (common_user_info_id) REFERENCES common_user_info (id);

ALTER TABLE common_user_info_university
    ADD CONSTRAINT fk_comuseinfuni_on_university FOREIGN KEY (university_id) REFERENCES university (id);

ALTER TABLE events_event_time
    ADD CONSTRAINT fk_eveevetim_on_event_time FOREIGN KEY (event_time_id) REFERENCES event_time (id);

ALTER TABLE events_event_time
    ADD CONSTRAINT fk_eveevetim_on_events FOREIGN KEY (events_id) REFERENCES events (id);

ALTER TABLE events_worth_events
    ADD CONSTRAINT fk_eveworeve_on_events FOREIGN KEY (events_id) REFERENCES events (id);

ALTER TABLE events_worth_events
    ADD CONSTRAINT fk_eveworeve_on_worth_events FOREIGN KEY (worth_events_id) REFERENCES worth_events (id);

ALTER TABLE resume_certificates
    ADD CONSTRAINT fk_rescer_on_certificate FOREIGN KEY (certificates_id) REFERENCES certificate (id);

ALTER TABLE resume_certificates
    ADD CONSTRAINT fk_rescer_on_resume FOREIGN KEY (resume_id) REFERENCES resume (id);

ALTER TABLE resume_courses
    ADD CONSTRAINT fk_rescou_on_course FOREIGN KEY (courses_id) REFERENCES course (id);

ALTER TABLE resume_courses
    ADD CONSTRAINT fk_rescou_on_resume FOREIGN KEY (resume_id) REFERENCES resume (id);

ALTER TABLE resume_jobs
    ADD CONSTRAINT fk_resjob_on_job FOREIGN KEY (jobs_id) REFERENCES job (id);

ALTER TABLE resume_jobs
    ADD CONSTRAINT fk_resjob_on_resume FOREIGN KEY (resume_id) REFERENCES resume (id);

ALTER TABLE resume_patents
    ADD CONSTRAINT fk_respat_on_patent FOREIGN KEY (patents_id) REFERENCES patent (id);

ALTER TABLE resume_patents
    ADD CONSTRAINT fk_respat_on_resume FOREIGN KEY (resume_id) REFERENCES resume (id);

ALTER TABLE resume_recomenadations
    ADD CONSTRAINT fk_resrec_on_recomenadation FOREIGN KEY (recomenadations_id) REFERENCES recomenadation (id);

ALTER TABLE resume_recomenadations
    ADD CONSTRAINT fk_resrec_on_resume FOREIGN KEY (resume_id) REFERENCES resume (id);

ALTER TABLE resume_skills
    ADD CONSTRAINT fk_resski_on_resume FOREIGN KEY (resume_id) REFERENCES resume (id);

ALTER TABLE resume_skills
    ADD CONSTRAINT fk_resski_on_skill FOREIGN KEY (skills_id) REFERENCES skill (id);

ALTER TABLE resume_volunteers
    ADD CONSTRAINT fk_resvol_on_resume FOREIGN KEY (resume_id) REFERENCES resume (id);

ALTER TABLE resume_volunteers
    ADD CONSTRAINT fk_resvol_on_volunteer FOREIGN KEY (volunteers_id) REFERENCES volunteer (id);

ALTER TABLE user_profile_hashtags
    ADD CONSTRAINT fk_useprohas_on_hashtags FOREIGN KEY (hashtags_id) REFERENCES hashtags (id);

ALTER TABLE user_profile_hashtags
    ADD CONSTRAINT fk_useprohas_on_user_profile FOREIGN KEY (user_profile_id) REFERENCES user_profile (id);

ALTER TABLE user_profile_interests
    ADD CONSTRAINT fk_useproint_on_interests FOREIGN KEY (interests_id) REFERENCES interests (id);

ALTER TABLE user_profile_interests
    ADD CONSTRAINT fk_useproint_on_user_profile FOREIGN KEY (user_profile_id) REFERENCES user_profile (id);